import pickle
import os
import subprocess
import glob
import time
import argparse
import sys

# ---------------- CONFIGURATION ----------------
EXTERNAL_SCRIPT_OUTPUT_DIR = "./eval_res_dic/" 
SCRIPT_PATH = "eomtAnomaly.py"
CONFIG_PATH = "./configs/dinov2/cityscapes/semantic/eomt_base_640.yaml"
LOAD_WEIGHTS = "../../epoch_106-step_19902_eomt.ckpt"

DATASETS_TO_TEST = {
    #"fs_static": r"..\..\Validation_Dataset\fs_static\images\*.jpg",
     "RoadAnomaly21": r"..\..\Validation_Dataset\RoadAnomaly21\images\*.png",
    #'RoadAnomaly': r'..\..\Validation_Dataset\RoadAnomaly\images\*.jpg',
    # 'RoadObstacle21': r'..\..\Validation_Dataset\RoadObsticle21\images\*.webp',
    # 'FS_LostFound': r'..\..\Validation_Dataset\FS_LostFound_full\images\*.png',
}

SCORES_TO_CHECK = ["rba"] # ["msp", "ml" , "me", "rba"]
# -----------------------------------------------

def get_latest_file(directory, extension="*.pkl"):
    """Finds the most recently created file in a directory."""
    files = glob.glob(os.path.join(directory, extension))
    if not files:
        return None
    latest_file = max(files, key=os.path.getctime)
    return latest_file

def load_pickle(path):
    if not os.path.exists(path):
        return {}
    try:
        with open(path, "rb") as f:
            return pickle.load(f)
    except Exception as e:
        print(f"Warning: Could not load pickle {path}: {e}")
        return {}

def save_pickle(data, path):
    with open(path, "wb") as f:
        pickle.dump(data, f)
    print(f"  -> Saved results to {path}")

def process_lora_directory(model_dir_abs):
    """
    Scans the specific model directory for all 'epoch-XX' subfolders 
    and evaluates them.
    """
    
    # 1. Find all epoch subdirectories
    epoch_dirs = sorted([
        d for d in os.listdir(model_dir_abs) 
        if os.path.isdir(os.path.join(model_dir_abs, d)) and d.startswith("epoch-")
    ])

    if not epoch_dirs:
        print(f"[!] No 'epoch-XX' directories found in {model_dir_abs}")
        return

    # 2. Load or initialize a local results file inside the model directory
    results_file_path = os.path.join(model_dir_abs, "evaluation_results.pkl")
    model_results = load_pickle(results_file_path)

    print(f"Found {len(epoch_dirs)} epochs to process in: {os.path.basename(model_dir_abs)}")

    # 3. Move to root directory for script execution context
    # (The script expects to run from the parent folder based on the os.chdir("../") at the top)
    # Note: We must ensure we are in the correct place relative to SCRIPT_PATH
    os.chdir("../") 
    
    for epoch_folder in epoch_dirs:
        print(f"\n--- Processing {epoch_folder} ---")
        
        full_lora_path = os.path.join(model_dir_abs, epoch_folder)
        
        if epoch_folder not in model_results:
            model_results[epoch_folder] = {}

        is_modified = False

        for dataset_name, dataset_path in DATASETS_TO_TEST.items():
            
            # Init dataset dict if needed
            if dataset_name not in model_results[epoch_folder]:
                model_results[epoch_folder][dataset_name] = {}

            existing_scores = model_results[epoch_folder][dataset_name].keys()
            missing_scores = [s for s in SCORES_TO_CHECK if s not in existing_scores]
            
            if not missing_scores:
                print(f"  [OK] {dataset_name}: All scores present.")
                continue

            scores_arg = ",".join(missing_scores)
            print(f"  [>>] {dataset_name}: Running for {missing_scores}...")

            cmd = [
                "python", SCRIPT_PATH,
                "--input", dataset_path,
                "--anomalyScore", scores_arg,
                "--config", CONFIG_PATH,
                "--loadWeights", LOAD_WEIGHTS,
                "--lora_weights", full_lora_path,
                "--save_res_dict", "True"
            ]

            try:
                start_time = time.time()
                # Run the external script
                subprocess.run(cmd, check=True, shell=False)
                
                # Retrieve the output file generated by the script
                latest_pkl = get_latest_file(EXTERNAL_SCRIPT_OUTPUT_DIR)
                
                if latest_pkl and os.path.getctime(latest_pkl) > start_time:
                    new_results = load_pickle(latest_pkl)
                    
                    # Merge new results into our storage
                    model_results[epoch_folder][dataset_name].update(new_results)
                    is_modified = True
                    print(f"  [V] Results merged successfully.")
                else:
                    print(f"  [X] Error: Output file not found or outdated for {dataset_name}")

            except subprocess.CalledProcessError as e:
                print(f"  [X] Script Execution Error: {e}")
            except Exception as e:
                print(f"  [X] Unexpected Error: {e}")

        # Save after every epoch to prevent data loss
        if is_modified:
            save_pickle(model_results, results_file_path)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate a specific LoRA model directory across all its epochs.")
    parser.add_argument("--model_dir", type=str, required=True, help="Path to the specific LoRA model directory (e.g. ./lora_weights/xyz_123)")
    
    args = parser.parse_args()

    # Convert to absolute path BEFORE changing directory, 
    # because the script does os.chdir("../")
    abs_model_dir = os.path.abspath(args.model_dir)

    if not os.path.exists(abs_model_dir):
        print(f"Error: Directory {abs_model_dir} does not exist.")
        sys.exit(1)

    process_lora_directory(abs_model_dir)